[package]
name = "aoc"
version = "0.1.0"
authors = ["Iain McCoy <iain@mccoy.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
